package globalData

import main.pageData
import scala.collection.mutable.ArrayBuffer

/**
 * @author dd

 */

// This object contains pool of data
// The data contains names, date of births, places, posts , 
// BASE64 encoded images , page titles and page details 
// Data is chosen randomly from this dataPool

object dataPool{

  val name = Array("Rafael","Fidel","Bradford","Aaron","Mitch","Everett",
  "Denny","Casey","Nicolas","Reginald","Gail","Derrick","Arnold","Sean",
  "Tyler","Joseph","Rosendo","Robby","Mel","Basil","Hershel","Jeremiah","Isaias",
  "Brandon","Bert","Hai","Lance","Dane","Les","Cristobal","Brady","Otto","Mauro",
  "Santiago  ","Damon  ","Chi  ","Ulysses  ","Edward  ","Fred  ","Amado  ","Dominic  ","Ramiro  ","Ashley  ",
  "Ferdinand  ","Conrad  ","Benito  ","Duncan  ","Dennis  ","Antonio  ","Cole  ","Alix  ","Shenita  ",
  "Marquita  ","Ka  ","Kimberlee  ","Florene  ","Malorie  ","Grazyna  ","Hanna  ","Shani  ","Lashon  ",
  "Winter  ","Sherilyn  ", "Ola  ","Melia  ","Zula  ",
  "Jenelle  ","Lakeesha  ","Britta  ","Regan  ","Michelle  ","Annie  ","Sarai  ",
  "Danita  ","Maragaret  ","Temple  ","Felipa  ","Belva  ","Angelina  ","Leola  ","Amal  ","Janee  ","Kai  ","Nikia  ",
  "Christinia  ","Madalene  ","Jenni  ","Adelina  ","Lorette  ","Sheri  ","Fredricka  ","Zelma  ","Amberly  ",
  "Tiffanie  ","Adria  ","Valencia  ","Usha  ","Mandi  ","Babara  ","Ima  ")  

  val dob = Array("12 March 1941","8 January 1948","6 August 1948","20 July 1951","25 October 1952","14 February 1954",
  "11 February 1955","4 December 1962","18 May 1965","21 October 1965","29 October 1966","31 May 1969","19 July 1973",
  "22 February 1974","25 June 1977", "9 July 1977","27 March 1983","14 September 1983","1 November 1985",
  "6 December 1987","30 September 1997","25 November 1998","13 September 1999","1 December 2000","23 September 2001")

  val placeOfBirth = Array("Los Angeles; California","Houston; Texas","Philadelphia; Pennsylvania","Phoenix; Arizona","San Antonio; Texas",
  "San Diego; California","Dallas; Texas","San Jose; California","Austin; Texas","Jacksonville; Florida","Indianapolis; Indiana",
  "San Francisco; California","Columbus; Ohio","Fort Worth; Texas","Charlotte; North Carolina","Detroit; Michigan","El Paso; Texas",
  "Memphis; Tennessee","Boston; Massachusetts","Seattle; Washington","Denver; Colorado","Washington; DC","Nashville-Davidson; Tennessee",
  "Baltimore; Maryland","Louisville/Jefferson; Kentucky","Portland; Oregon","Oklahoma ; Oklahoma","Milwaukee; Wisconsin","Las Vegas; Nevada",
  "Albuquerque; New Mexico","Tucson; Arizona","Fresno; California","Sacramento; California","Long Beach; California","Kansas ; Missouri",
  "Mesa; Arizona","Virginia Beach; Virginia","Atlanta; Georgia","Colorado Springs; Colorado","Raleigh; North Carolina","Omaha; Nebraska","Miami; Florida",
  "Oakland; California","Tulsa; Oklahoma","Minneapolis; Minnesota","Cleveland; Ohio","Wichita; Kansas","Arlington; Texas","New Orleans; Louisiana",
  "Bakersfield; California","Tampa; Florida","Honolulu; Hawaii","Anaheim; California","Aurora; Colorado","Santa Ana; California","St. Louis; Missouri",
  "Riverside; California","Corpus Christi; Texas","Pittsburgh; Pennsylvania","Lexington-Fayette; Kentucky","Anchorage municipality, Alaska","Stockton; California",
  "Cincinnati; Ohio","St. Paul; Minnesota","Toledo; Ohio","Newark; New Jersey","Greensboro; North Carolina","Plano; Texas","Henderson; Nevada",
  "Lincoln; Nebraska","Buffalo; New York","Fort Wayne; Indiana","Jersey ; New Jersey","Chula Vista; California","Orlando; Florida","St. Petersburg; Florida",
  "Norfolk; Virginia","Chandler; Arizona","Laredo; Texas","Madison; Wisconsin","Durham; North Carolina","Lubbock; Texas","Winston-Salem; North Carolina",
  "Garland; Texas","Glendale; Arizona","Hialeah; Florida","Reno; Nevada","Baton Rouge; Louisiana","Irvine; California","Chesapeake; Virginia",
  "Irving; Texas","Scottsdale; Arizona","North Las Vegas; Nevada","Fremont; California","Gilbert town, Arizona","San Bernardino; California",
  "Boise; Idaho","Birmingham; Alabama")
  
  val posts=Array("I'm gonna make him an offer he can't refuse.:THE GODFATHER",
"You don't understand! I coulda had class. I coulda been a contender. I could've been somebody, instead of a bum, which is what I am.:ON THE WATERFRONT",
"Toto, I've a feeling we're not in Kansas anymore.:THE WIZARD OF OZ",
"Here's looking at you, kid.:CASABLANCA",
"Go ahead, make my day.:SUDDEN IMPACT",
"All right, Mr. DeMille, I'm ready for my close-up.:SUNSET BLVD.",
"May the Force be with you.:STAR WARS",
"Fasten your seatbelts. It's going to be a bumpy night.:ALL ABOUT EVE",
"You talking to me?:TAXI DRIVER",
"What we've got here is failure to communicate.:COOL HAND LUKE",
"I love the smell of napalm in the morning.:APOCALYPSE NOW",
"Love means never having to say you're sorry.:LOVE STORY",
"The stuff that dreams are made of.:THE MALTESE FALCON",
"E.T. phone home.:E.T. THE EXTRA-TERRESTRIAL",
"They call me Mister Tibbs!:IN THE HEAT OF THE NIGHT",
"Rosebud.:CITIZEN KANE",
"Made it, Ma! Top of the world!:WHITE HEAT",
"I'm as mad as hell, and I'm not going to take this anymore!:NETWORK",
"Louis, I think this is the beginning of a beautiful friendship.:CASABLANCA",
"A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.:THE SILENCE OF THE LAMBS",
"Bond. James Bond.:DR. NO",
"There's no place like home.:THE WIZARD OF OZ",
"I am big! It's the pictures that got small.:SUNSET BLVD.",
"Show me the money!:JERRY MAGUIRE",
"Why don't you come up sometime and see me?:SHE DONE HIM WRONG",
"I'm walking here! I'm walking here!:MIDNIGHT COWBOY",
"Play it, Sam. Play 'As Time Goes By.':CASABLANCA",
"You can't handle the truth!:A FEW GOOD MEN",
"I want to be alone.:GRAND HOTEL",
"After all, tomorrow is another day!:GONE WITH THE WIND",
"Round up the usual suspects.:CASABLANCA",
"I'll have what she's having.:WHEN HARRY MET SALLY",
"You know how to whistle, don't you, Steve? You just put your lips together and blow.:TO HAVE AND HAVE NOT",
"You're gonna need a bigger boat.:JAWS",
"Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges!:THE TREASURE OF THE SIERRA MADRE",
"I'll be back.:THE TERMINATOR",
"Today, I consider myself the luckiest man on the face of the earth.:THE PRIDE OF THE YANKEES",
"If you build it, he will come.:FIELD OF DREAMS",
"My mama always said life was like a box of chocolates. You never know what you're gonna get.:FORREST GUMP",
"We rob banks.:BONNIE AND CLYDE",
"Plastics.:THE GRADUATE",
"We'll always have Paris.:CASABLANCA",
"I see dead people.:THE SIXTH SENSE",
"Stella! Hey, Stella!:A STREETCAR NAMED DESIRE",
"Oh, Jerry, don't let's ask for the moon. We have the stars.:NOW, VOYAGER",
"Shane. Shane. Come back!:SHANE",
"Well, nobody's perfect.:SOME LIKE IT HOT",
"It's alive! It's alive!:FRANKENSTEIN",
"Houston, we have a problem.:APOLLO 13",
"You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?:DIRTY HARRY",
"You had me at hello:JERRY MAGUIRE",
"One morning I shot an elephant in my pajamas. How he got in my pajamas, I don't know.:ANIMAL CRACKERS",
"There's no crying in baseball!:A LEAGUE OF THEIR OWN",
"La-dee-da, la-dee-da.:ANNIE HALL",
"A boy's best friend is his mother.:PSYCHO",
"Greed, for lack of a better word, is good.:WALL STREET",
"Keep your friends close, but your enemies closer.:THE GODFATHER II",
"As God is my witness, I'll never be hungry again.:GONE WITH THE WIND",
"Well, here's another nice mess you've gotten me into!:SONS OF THE DESERT",
"Say to my little friend!:SCARFACE",
"What a dump.:BEYOND THE FOREST",
"Mrs. Robinson, you're trying to seduce me. Aren't you?:THE GRADUATE",
"Gentlemen, you can't fight in here! This is the War Room!:DR. STRANGELOVE",
"Elementary, my dear Watson.:THE ADVENTURES OF SHERLOCK HOLMES",
"Take your stinking paws off me, you damned dirty ape.:PLANET OF THE APES",
"Of all the gin joints in all the towns in all the world, she walks into mine.:CASABLANCA",
"Here's Johnny!:THE SHINING",
"They're here!:POLTERGEIST",
"Is it safe?:MARATHON MAN",
"Wait a minute, wait a minute. You ain't heard nothin' yet!:THE JAZZ SINGER",
"No wire hangers, ever!:MOMMIE DEAREST",
"Mother of mercy, is this the end of Rico?:LITTLE CAESAR",
"Forget it, Jake, it's Chinatown.:CHINATOWN",
"I have always depended on the kindness of strangers.:A STREETCAR NAMED DESIRE",
"Hasta la vista, baby.:TERMINATOR 2: JUDGMENT DAY",
"Soylent Green is people!:SOYLENT GREEN",
"Open the pod bay doors, please, HAL.:2001: A SPACE ODYSSEY",
"Striker: Surely you can't be serious.:AIRPLANE!",
"Rumack: I am serious...and don't call me Shirley.:AIRPLANE!",
"Yo, Adrian!:ROCKY",
"Hello, gorgeous.:FUNNY GIRL",
"Toga! Toga!:LAMPOON'S ANIMAL HOUSE",
"Listen to them. Children of the night. What music they make.:DRACULA",
"Oh, no, it wasn't the airplanes. It was Beauty killed the Beast.:KING KONG",
"My precious.:THE LORD OF THE RINGS: TWO TOWERS",
"Attica! Attica!:DOG DAY AFTERNOON",
"Sawyer, you're going out a youngster, but you've got to come back a star!:42ND STREET",
"Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go!:ON GOLDEN POND",
"Tell 'em to go out there with all they got and win just one for the Gipper.:KNUTE ROCKNE ALL AMERICAN",
"A martini. Shaken, not stirred.:GOLDFINGER",
"Who's on first.:THE NAUGHTY NINETIES",
"Cinderella story. Outta nowhere. A former greenskeeper, now, about to become the Masters champion. It looks like a mirac...It's in the hole! It's in the hole! It's in the hole!:CADDYSHACK",
"Life is a banquet, and most poor suckers are starving to death!:AUNTIE MAME",
"I feel the need - the need for speed!:TOP GUN",
"Carpe diem. Seize the day, boys. Make your lives extraordinary.:DEAD POETS SOCIETY",
"Snap out of it!:MOONSTRUCK",
"My mother thanks you. My father thanks you. My sister thanks you. And I thank you.:YANKEE DOODLE DANDY",
"Nobody puts Baby in a corner.:DIRTY DANCING",
"I'll get you, my pretty, and your little dog, too!:WIZARD OF OZ, THE",
"I'm the king of the world!:TITANIC")

val imageBase64 = Array("4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxQTEhUUExQWFhUXGB8YGBgYGBgcGhkeHB0YHxoaGBweICggHB0lHBoXITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGxAQGiwkHCQsLCwsLCwsLCwsLCwsLCwsLCwsLCwuLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLP",
    "XFhYVFhcXGBcYFxUWGBoYHCggHxwmHBcVITEhJSkrLi4uGB8zODMsNygtLisBCgoKDg0OGxAQGywkHyUsLDQsLDQsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLP",
    "4AAQSkZJRgABAgEASABIAAD/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAgICAgICAgICAgMDAwMDAwMDAwMBAQEBAQEBAgEBAgICAQICAwMDAwMDCABEIAqwDwAMBEQACEQEDEQH/xAAfAAEAAQQDAQEBAAAAAAAAAAAABwYICQoEBQsDAgH",
    "4AAQSkZJRgABAQEBLAEsAAD/4iH8SUNDX1BST0ZJTEUAAQEAACHsTktPTgIgAABtbnRyUkdCIFhZWiAH2QACABQAEQAHAAphY3NwQVBQTAAAAABub25lAAAAAQAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLQAAAAAAAAAAAA",
    "4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxQTEhUUExQWFRUWGRwaGBgYFx4gGxofHR4cHhwfHhwcHCgkHxolHB4dIjEiJSkrLi4uGSAzODUsNygtLisBCgoKDg0OGxAQGywmHyQ0Ly8sNCwsLC8sLDQsLC8sLCwsNCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLP",
"4VLoRXhpZgAASUkqAAgAAAALAA8BAgAGAAAAkgAAABABAgAPAAAAmAAAABIBAwABAAAAAQAAABoBBQABAAAAuAAAABsBBQABAAAAwAAAACgBAwABAAAAAgAAADIBAgAUAAAAyAAAADsBAgABAAAAAAAAABMCAwABA")    


val page_titles = Array("Liverpool FC","Florida Gators","Pink Floyd","Roger Federer","The Shawshank Redemption")
val page_info = Array("Official Facebook page of Liverpool FC, 18 times champions of England and 5 times champions of Europe.",
                      "The Official Facebook page of the Florida Gators.",
                      "Pink Floyd were an English rock band formed in London. They achieved international acclaim with their progressive and psychedelic music.",
                      "This is Roger Federer's official Facebook Page. Roger is a Swiss professional tennis player. Many sports analysts, tennis critics, and former and current players consider Federer to be the greatest tennis player of all time.",
                      "The Shawshank Redemption is a 1994 American drama film written and directed by Frank Darabont, and starring Tim Robbins and Morgan Freeman.")    

}
